services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "8800:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_SERVERNAME: db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE: ${MYSQL_DATABASE}
      DB_PORT: 3306
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    # Define volume for persisting MySQL data
